### ISSUE TITLE
Some videos don't play at all

### ISSUE THREAD

**Issue by rEnr3n** [Docile-Alligator/Infinity-For-Reddit#1058]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.0

### Where did you get the app from

Google Play

### Android version

11

### Device model

realme 6i

### First occurred

When I first installed the app yesterday

### Steps to reproduce

1. Open this link in the app: https://www.reddit.com/r/twice/comments/x3a4n2/220901_dahyun_prevents_momo_from_walking_between/
2. Play video

### Expected behaviour

The video should play.

### Current behaviour

I just see a black screen.

**Comment by rEnr3n** [comment]
I read that [phone support](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues/510#issuecomment-1014124836) may be the issue here. I opened the link in the official reddit app and I was able to play the video. Are they using some workarounds? Can we use some workarounds here too?

**Comment by Wladefant** [comment]
It does play perfectly for me

**Comment by amayra** [comment]
only NSFW is not working

**Comment by gabey14** [comment]
Facing the same issue.

**Comment by yephny** [comment]
@rEnr3n Wait long enough, and you'll see the error: "Fetch Gfycat video failed". It has nothing to do with how old your phone is. Chances are, your DNS server is blocking it, so use a different DNS server/service. Popular, but not private, choices are Google's `8.8.8.8` and Cloudflare's `1.1.1.1`.

**Comment by rEnr3n** [comment]
> Wait long enough, and you'll see the error: "Fetch Gfycat video failed".

I waited at least 5 minutes and I didn't see any kind of error message.

> As a workaround, you can copy the video link and watch it with any other app.

It doesn't seem like a dns issue. I opened the gfycat link on the browser and the official reddit app and it played just fine.

**Comment by gabey14** [comment]
Yes right it seems like some other issue

**Comment by yephny** [comment]
@rEnr3n I get different results on Wifi and mobile network, that's why I brought up DNS. If you haven't tried out another DNS provider, you could just connect using a VPN and test it that way to rule out the possible DNS issue.

![This is the link that I'm talking about.](https://a.pomf.cat/ctmhzg.png)

**Comment by BLucky-gh** [comment]
Its definitely not a dns issue, I have set my dns to 8.8.8.8 and monitored my dns requests and the requests just went to domains like redgifs and stuff which are not in my blocklist. Also I can just open the same link in the browser and official reddit app.

This is also not and hdr issue since my phone is hdr capable

**Comment by rEnr3n** [comment]
@yephny I changed my dns server to 8.8.8.8 and 1.1.1.1. Rebooted the phone right after every change. I see the same domain in your screenshot via Share in all instances.

**Comment by Triplesweet** [comment]
I tried 1.1.1.1 didn't work, used a VPN still no video, tried other Front ends still no results, 

Is there a possibility that reddit changed how NSFW videos are handled? Since I didn't see any problem on normal videos

**Comment by BLucky-gh** [comment]
> Is there a possibility that reddit changed how NSFW videos are handled?

Yup, this might be related to #1057

**Comment by rEnr3n** [comment]
> Is there a possibility that reddit changed how NSFW videos are handled?

The link on my post is not NSFW.

**Comment by BLucky-gh** [comment]
So far from what I have read across a couple issues on this repo it seems that it's gfycat and redgifs acting up, We already know what's up with redgifs so I wonder if gfycat also changed its api or smth

**Comment by Manson-22** [comment]
> So far from what I have read across a couple issues on this repo it seems that it's gfycat and redgifs acting up, We already know what's up with redgifs so I wonder if gfycat also changed its api or smth

Good to know, thought infinity was bugging.

**Comment by rEnr3n** [comment]
I'm only getting this issue when I play the video directly. When I `Share Video Link` > `Handle Link`, the video plays.

Another thing I found is that some of the videos have dropped frames. Using the trick above plays the video smoothly. Example: https://www.reddit.com/r/twice/comments/x4a1ut/220828_pretty_sana/

**Comment by yephny** [comment]
@rEnr3n Could that be because the video plays from Redgifs or whatever the host is, but you play the video on reddit's servers if you share video link?

**Comment by Domefemia** [comment]
I'm experiencing the same problem. This are my info:
App version: 5.3.0
Where did you get the app from: Playstore
Android version: 12/11
Device model: Poco x3 nfc

All the links I'm encountering, that have this problem, are the one inside nsfw subreddit, and they are all like this "https://v.redd.it/<id>/DASH_1080.mp4". But instead "https://i.redd.it/<id>.gif" and "https://i.imgur.com/<id>.mp4" are working fine!

**Comment by BeatLink** [comment]
I too face the same issue. The issue only started within the last few months and seems to only affect nsfw sites especially redgifs

**Comment by BeatLink** [comment]
Also of note is that downloading the videos via the buttons work fine. Only playing doesnt seem to work

**Comment by Wladefant** [comment]
The new release with the redgif fix is now out https://github.com/Docile-Alligator/Infinity-For-Reddit/releases/tag/v5.3.1

**Comment by rEnr3n** [comment]
Updated to v5.3.1. I still get the same issues; video not playing or video playing with dropped frames. Workaround still works.

**Comment by BeatLink** [comment]
My redgifs issue was resolved so perhaps there are two bugs at play?

**Comment by Maxplosion** [comment]
same issue here, workaround stated using 'handle link' works but is very tedious.

**Comment by Para-lyzed** [comment]
I'd like to follow up by adding a new I see this behavior with. The video linked in the original issue actually plays fine for me, but I found [this post](https://www.reddit.com/r/BetterEveryLoop/comments/z1te2l/what_uh_what/) on r/BetterEveryLoop (that also *isn't* NSFW, so that isn't the issue) that presents the same behavior as described in the original issue. The handle link workaround doesn't work for me with this particular video.

Video plays perfectly fine if I open it in my browser (Bromite), so it also is not a DNS issue or anything similar. The issue persists both with and without a VPN. I never get an error message even after waiting multiple minutes, just like the original issue. This is not the only video I've had this issue with, but it happens so infrequently that I only got around to attempting to report the issue now and didn't save any other videos with the same behavior. I have the automatically try accessing redgifs option enabled, and I don't see any other relevant options, but could include whatever options anyone thinks may be relevant. I am not using a Reddit account, just the default "Anonymous" user. The video is an i.imgur.com link, but I am able to open other videos of that type through Infinity just fine. I have tried force stopping, restarting, clearing cache, and the handle link workaround mentioned in this thread. I have not tried reinstalling, but if others cannot replicate this behavior, that will be my next step.

Does this video have the same behavior for anyone else?

**Comment by rharish101** [comment]
@Para-lyzed I can confirm that I can't view that video with Infinity (as a signed-in user), but it works fine with the "handle link" workaround (using VLC), and with a browser.

**Comment by rEnr3n** [comment]
@Para-lyzed I have the same results as you are.

@rharish101 When you say it works with "handle link" workaround using vlc, are you talking about the "Play with VLC"? The one with the vlc logo? The "handle link" I referred to was the one that has the Infinity logo. I also have the same results as yours with vlc and the browser (plays fine).

**Comment by rharish101** [comment]
My bad, you're right. The handle link workaround didn't work.

**Comment by Para-lyzed** [comment]
I did notice that the link directly to the video was an http link instead of https (http://i.imgur.com). I had previously said I could open i.imgur.com links fine, but the only other video I compared it to was an https link (https://i.imgur.com). After having noticed that, I went back to r/BetterEveryLoop to see if I could find other videos.

I found [this post](https://www.reddit.com/r/BetterEveryLoop/comments/zb865g/jump_forward_fall_back_take_a_nap/) which presents with the same issue and *also* uses an http link instead of https. I then found [another post](https://www.reddit.com/r/BetterEveryLoop/comments/zannex/you_crepey_bastard/) with the same issue, also with http.

I think that the behavior I'm seeing is most likely the result of this http discrepancy. Since the post in the original issue does not appear to be caused by the same issue, I will open a new issue now that I have a better idea what the problem may be.

**Comment by Docile-Alligator** [comment]
@Para-lyzed Your issue is fixed.
@rEnr3n This video is an HDR video. If your phone does not support it, it will not play.

**Comment by rEnr3n** [comment]
> This video is an HDR video. If your phone does not support it, it will not play.

Doesn't explain why the video plays fine with other apps on the SAME hardware. Tried with browser, vlc and the official reddit app and the video plays fine. Only Infinity can't.
