### ISSUE TITLE
Filters broken

### ISSUE THREAD

**Issue by Donkey-Doug** [Docile-Alligator/Infinity-For-Reddit#1059]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

0.5.3

### Where did you get the app from

F-Droid

### Android version

10

### Device model

Xiaomi Mi 9T Pro

### First occurred

Always been the case

### Steps to reproduce

So I press on the floating button and there is an animation, but nothing is filtered. I then press again on the floating button and now I can select some things to filter, but for some reason I can name and save my filter from this screen. So instead of having to manually select filters I tried to create default filters (like only gifs and videos), but I don't know how to apply a filter I created.

Also when not saving but just filtering, the results are very incomplete. For example, open any subreddit, filter on a type (say pics or text) and apply the filter. This then does not show all posts matching the filter description. I think filters in general are broken in this app.

And why can I not sort and filter at the same time?

### Expected behaviour

Select some filters and apply them.

### Current behaviour

I have no clue how filters work right now.

### Logs

-

**Comment by user-727** [comment]
I don't think this is a bug, but more of a usability error. Post filters are definitely not very user friendly, but once you get the hang of it they can be very powerful and are actually quite easy to understand how they work. If you'd like, I'd be happy to help you with setting up your filters, you can DM me on Reddit directly (reddit.com/u/user_727) or send me your Discord ID if you'd prefer that.

**Comment by KaKi87** [comment]
> I press on the floating button and there is an animation, but nothing is filtered. I then press again on the floating button and now I can select some things to filter, but for some reason I can name and save my filter from this screen. So instead of having to manually select filters I tried to create default filters (like only gifs and videos), but I don't know how to apply a filter I created.

I'm experiencing the same thing.
> Post filters are definitely not very user friendly, but once you get the hang of it they can be very powerful and are actually quite easy to understand how they work

How about a tutorial ?

> If you'd like, I'd be happy to help you with setting up your filters, you can DM me on Reddit directly (reddit.com/u/user_727) or send me your Discord ID if you'd prefer that.

I would prefer a tutorial right here, as that's what GitHub is for.

Thanks

**Comment by user-727** [comment]
`I would prefer a tutorial right here, as that's what GitHub is for.`

Well I'm not a developer for the app, just a random dude trying to help, so I don't really want to make an "official" guide because I don't think it's my place to do so.

But my advice would be to ditch the floating filter button altogether, as it's more confusing than anything. In my opinion, you should really only mess with filters in the post filter settings (from the navigation drawer on the left, go to "Settings", and then select "Post Filter").

Once there, click the blue plus button that should be on the bottom right of the screen to create a new post filter. I don't kow what exactly you're trying to do with the filter, and most of the options on that screen are pretty self explanatory, but definitely let me know if you're having trouble doing what you're trying to do and I'd be happy to help you configure the actual filter.

When you're happy with your filter, click the floppy disk icon at the top right to save it. You will now be brought back to the previous screen, where you should see the filter you just created in the list (it's way easier to organize them if you give them distinctive names, particularly if you have a lot of them).

Now comes the most important but also most easy to miss part, applying the actual filter to the desired feed. You see, the post filters you create don't actually do anything until you apply them to a feed (a subreddit, user, multireddit, etc.).

To do that, just tap on the filter you just created, and select "Apply to". On that screen, press the blue plus icon on the bottom right again, and select which feed you want the filter to be applied to. Be careful if you select "Subreddit" or "User" though, as you need to only use lowercase characters (and as the tooltip says, omit the "r/" or "u/" prefix).

For example, to apply the filter to the r/popular subreddit, simply write "popular" in the field (without the quotes).

If you want to apply the filter to a multireddit, you will need to first have that multireddit on your own account first as I'm pretty sure there's a bug at the moment making it impossible to use another user's multireddit, if that's something you wanted to do. In that case, just go to the new Reddit redesign on a web browser, and while viewing the desired multireddit feed, select the "Duplicate" option in the three dots menu on the top right.

For example, to apply the filter to a multireddit called "Test1" on your account, write "/user/kaki87/m/test1/" in the field (without the quotes, and in all lowercase characters as previously mentionned).

And now the filter will be applied to that feed automatically when you visit it. If you want to modify the filter, my recommendation would again to go through the settings page, and not the floating button.

**Comment by KaKi87** [comment]
So, a filter cannot be toggled on/off in one-click from any feed ?

**Comment by Donkey-Doug** [comment]
Correct. It is really weird. And when it works, the filters are not correct. For example, open a subreddit, filter for pictures, what you see are not all the pictures because some are somehow missing.

Filters are simply broken. No way this is intended behaviour.

**Comment by KaKi87** [comment]
Okay.
How about applying a filter to an anonymous multireddit ?

**Comment by Donkey-Doug** [comment]
I am not sure what you are asking and why.

All that needs to happen is this:

1. Click on filter
2. A new page or popup window lets you choose from:
     - Pictures
     - Galleries
     - Gifs
     - Videos
     - Text
     - Link
3. Click every option you want and press ok. The posts should be filtered.
4. Optional: Add an advanced settnmg option to the popup window for regex or something.

**Comment by KaKi87** [comment]
> to apply the filter to a multireddit called "Test1" on your account, write "/user/kaki87/m/test1/"

I'm asking how to do the same with a multireddit belonging to an anonymous Infinity account :

![](https://cdn.discordapp.com/attachments/493524617714204672/1018816290061832232/Screenshot_20220912-113129_Infinity-01.jpeg)

Thanks

**Comment by KaKi87** [comment]
Additionally, is it possible to apply a filter to a specific subreddit but in *home* ? Thanks

**Comment by user-727** [comment]
> Additionally, is it possible to apply a filter to a specific subreddit but in _home_ ? Thanks

Yes, by selecting "subreddit" when selecting where to apply the post filter to, that filter will be applied to the subreddit when you directly visit it (via the search for example), but also in the home feed.

Concerning the anonymous multireddit, I haven't done a lot of tests because I don't personally use that functionality, but I don't think that is something that is doable at the moment.
