### ISSUE TITLE
Comment sorting method not saving

### ISSUE THREAD

**Issue by BicBoiSpyder** [Docile-Alligator/Infinity-For-Reddit#1233]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

F-Droid

### Android version

GrapheneOS Android 13 Build TP1A.221105.002.2022111000

### Device model

Google Pixel 6 Pro

### First occurred

First noticed a few days ago.

### Steps to reproduce

1. Open any post to view comments. Comments will be sorted by "Best."
2. Open three dot menu on top right > "Sort" > select sort by "Top" and it will work as intended.
3. Back out of post and open the same post again. The sorting method will revert back to "Best."

### Example post, link, markdown...

https://streamable.com/3epdi2

### Expected behaviour

After sort method has been changed, I should stay set to the method selected.

### Current behaviour

Does not save sorting method.

**Comment by us3rname101** [comment]
This is a bug in 5.3.4 but it has been fixed in a newer commit [0ae9b74](https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/ff10eb5f92810f2f1a1ca2ba5617a035957509ad). 
You can download an actions build and install one of the provided apks.
Best to leave this issue open until a version push is committed so other issues are not created.
