### ISSUE TITLE
Error loading posts. Tap to retry.

### ISSUE THREAD

**Issue by amogusussy** [Docile-Alligator/Infinity-For-Reddit#1540]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.0.2

### Where did you get the app from

F-Droid

### Android version

ColorOS V7.2

### Device model

Oppo A15

### First occurred

about 3-4 days ago.

### Steps to reproduce

I just opened Infinity, and I get an error message saying 'Error loading posts. Tap to retry.'
There aren't really any specific steps to it.

### Example post, link, markdown...

http://0.vern.cc/bU.jpg

### Expected behaviour

Posts should load.

### Current behaviour

It doesn't load anything.

**Comment by TurtleMeds** [comment]
Same issue here on Oxygen OS

**Comment by PVTejas** [comment]
Same issue on LineageOS 19.1

Maybe API changes being enforced?

**Comment by DeBlue7** [comment]
I have the same issue. 

Galaxy a52 OneUi 5.1

**Comment by sbor23** [comment]
Same. Must be the API changes. Any confirmation from the devs maybe? Is there an official guide to include a personal API key?

**Comment by Andoriax** [comment]
Ditto.
Current app version on Graphene (Android).
Any variations of App Info settings prove irrelevant.

Website logs in fine.
App recognizes credentials and account by still showing the avatar and subscribed subreddit list, but stays on an error message:

"Web page not available
The web page at reddit://reddit/?_branch_referrer=H4sIAAAAAAAAA6VTy27bMBD8GukiQJYlO04LEIXjwi2QBEiRtD0StLiWNuJDISnL6dd3ablFjRbIodCB4uzsa3bZhtD797OZAykx5KLvc4Wmm32QVgs0bBzH%2FGyrrU4bsNjz2g4muFf29TEdPDguGjCB3dsfqJRIyu0yL7KkvL5DMxyT6iZbG%2BksymxexdsDHkFlq%2BzB2exmQCXJ4%2BlLtc7LqrguyLeYR9p4SMp32brvFXyH3S2GGLha5dVVjH37%2Ben%2BLik3mcIOsk9QdzbSv4HzaA1RF1TDpnVWA13m81VexC%2B7tztUkD2KvXD4O2K6Ex744BQjKKm2ewCZVB9b8k6VMM1AHTIwqaQ290J5SEmMXtSBHxBGFtwAqZA7ZevubPfgYyEcJevEy17W%2BvlFvzS7Dp%2BtmFQjU1nOi%2BWqLJYLqmNCjdDANgpcpyAdguYBnKYMIIImlfmCmna94hobJ0JMYY16PTE1SBw00yPsiBSPE%2Bzt4Gpgx57EIJE208%2FJdEoWiXwCuYOD0D0%2FVMTz7TT4P%2B21Nd4qlFNmqiOtiS%2BwMf8bphXGgPqryj31PTi4aKqD19E6%2BbYoSbmwDRUj0UEdWBt3PanWccbl9nKzCYh0CdDH%2Fee9CC07g2JaX35pnHwj5dSZIgYLJfcrDHi0%2FYSeB11dsX%2FgF6MOovGMnh%2F3oKhY67i2Uqhfiin0AU1zmhqpF%2BKDe5P9E6aeA6DdAwAA&link_click_id=1230862534559540244 could not be loaded because:

net::ERR_UNKNOWN_URL_SCHEME

**Comment by Docile-Alligator** [comment]
Please relogin your account. The old API was deleted and thus the issue happens.
