### ISSUE TITLE
Posts not loading on the username profile page

### ISSUE THREAD

**Issue by AlexJoaquimPereira** [Docile-Alligator/Infinity-For-Reddit#1647]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.1.1

### Where did you get the app from

Other

### Android version

12

### Device model

Poco M2 Pro

### First occurred

Last night

### Steps to reproduce

1. Open Infinity
2. Go to your profile/any username's profile
3. The posts won't be seen and it will show an error

This behaviour is seen both on WiFi and cellular.

### Example post, link, markdown...

![IMG_20240529_124930](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/126944853/ff7c725c-6e0a-422f-9f3d-5303a84ae839)

(Blurred to maintain privacy)

Comments are visible.

### Expected behaviour

It should show the posts as usual.

### Current behaviour

Error showing posts.
Tap to retry.

**Comment by Docile-Alligator** [comment]
It's because the network library i used automatically added a trailing slash after the URL.

It should be
https://oauth.reddit.com/user/Hostilenemy/submitted.json?sort=new,
but it became https://oauth.reddit.com/user/Hostilenemy/submitted.json/?sort=new

Notice there is an unwanted slash after .json.

And this problem only occurs when there is an authorization header present, so you can still browse user posts in the anonymous mode.

And the funny thing is that there is no trailing slash added when you browse "upvoted", "downvoted", etc posts, even when you are logged in. They use the same variable and method to construct the url.

https://oauth.reddit.com/user/Hostilenemy/upvoted.json?sort=new is fine. Not "submitted".

But I believe Reddit has changed something recently because this problem has been there forever I guess, and I am only aware of it right now.

It seems other 3rd party clients have this problem as well?

Feel free to suggest some possible solutions. Thank you!

**Comment by Docile-Alligator** [comment]
Infinity does not have issue in the anonymous mode as well.
Please try boost and now for reddit.

**Comment by marovira** [comment]
I can confirm that boost (patched with ReVanced) has the same issue. Only difference with Infinity is that anonymous mode doesn't show posts as well.

**Comment by Docile-Alligator** [comment]
"ted", "sbtted", "subtted", "submtted", "itted", "mitted", "ubmi", "ubmitt", "ubmitt", "umitted", "ubmitted", "sutd", "suttd", "subttd", "sued", "submt", "sitted", "subitted", "submtted" and "submied" have no problem.

"submitted", "submited", "submitd"and "submit", have problem.

I guess there should not be any "submit" inside the url path??????????

**Comment by Docile-Alligator** [comment]
Yes I understand. The url matters. Maybe it will have the same problem if it uses oauth.reddit.com.

**Comment by Docile-Alligator** [comment]
Actually it happens when there is a user agent header field + the word "submit" inside a relative url.

The workaround is to remove the user agent in the header when fetching user posts.

**Comment by Docile-Alligator** [comment]
Fixed it by removing the user agent header. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/392ea8ee9b62b8bcf2c03399d56e47a0394758d4
