### ISSUE TITLE
can not submit any post!

### ISSUE THREAD

**Issue by allentown521** [Docile-Alligator/Infinity-For-Reddit#1699]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.3.0

### Where did you get the app from

Other

### Android version

android 14

### Device model

oneplus 12

### First occurred

now

### Steps to reproduce

submit any post (text or image) on my phone is impossible ,but works fine on emulator.
i found that SubmitPostService never run:
![image](https://github.com/user-attachments/assets/8c50e6be-6bc0-42d3-ab70-4e1f9d684acd)

**Comment by allentown521** [comment]
system_server                        E  Error getting package info: ml.docilealligator.infinityforreddit.debug

not sure if had relation with this issue

**Comment by allentown521** [comment]
![image](https://github.com/user-attachments/assets/f3d0f070-3555-4630-9cdf-0e70ff3c5655)

**Comment by allentown521** [comment]
I found the problem. I turned on the VPN on my phone and it worked fine after this change:
    public static JobInfo constructJobInfo(Context context, long contentEstimatedBytes, PersistableBundle extras) {
//        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
//            return new JobInfo.Builder(JOB_ID++, new ComponentName(context, EditProfileService.class))
//                    .setUserInitiated(true)
//                    .setRequiredNetwork(new NetworkRequest.Builder().addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET).build())
//                    .setEstimatedNetworkBytes(0, contentEstimatedBytes + 500)
//                    .setExtras(extras)
//                    .build();
//        } else {
            return new JobInfo.Builder(JOB_ID++, new ComponentName(context, EditProfileService.class))
                    .setExtras(extras)
                    .build();
//        }
    }

**Comment by Corbachini33** [comment]
Same issue on 7.3.1

**Comment by SashaMcC** [comment]
Hi,

Can confirm this behaviour happens on builds with my own API key, package name and anything else after 7.30

I'm not using a proper VPN, but using Adguard Premium as a local VPN. Even with whitelist rules for any Reddit API URLs or anything else the app requests (if you search my recent commit history you can see URLs I tried to whitelist from filtering from even DPI with no success), it refuses to allow any downloads until the connection is stopped.

If there's any way I could help test this at all to help find a resolution, please let me know, I have the next few days off as public holidays and can test on a few different Pixels as well as stock AOSP through DSU loader if applicable 

Off-topic and hopefully not interrupting, besides that thank you for continuing to maintain the app. It genuinely makes Reddit as a platform bearable

**Comment by Docile-Alligator** [comment]
Hi @allentown521
Thank you. Yes I suspect `.setRequiredNetwork(new NetworkRequest.Builder().addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)` is the culprit. Android will first check if your wifi or cellular network can access the internet by going to `http://connectivitycheck.gstatic.com/generate_204`. If not successful, it will display a exclamation mark on your wifi or cellular icon on the status bar. And even if you can access reddit with a vpn, the Android system will not run the job.

Unfortunately, it's an Android 14's requirement to use this kind of implemtation. You can find more info here: https://developer.android.com/develop/background-work/background-tasks/uidt.

Did your Android system tell you there is no internet access when your VPN was not enabled?

**Comment by Docile-Alligator** [comment]
Hi @allentown521 @SashaMcC 

Thank you. Could you help me test different required network options by changing `NetworkCapabilities.NET_CAPABILITY_INTERNET` inside `.setRequiredNetwork(new NetworkRequest.Builder().addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET).build())` on line 126 in SubmitPostService? https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/bc6896946c87de72b0ad3291ef5f710ba09a67d1/app/src/main/java/ml/docilealligator/infinityforreddit/services/SubmitPostService.java#L126

And then try to build the app and run it on your phone to see if you can submit a post?

The values I would like you to test are:
`NetworkCapabilities.NET_CAPABILITY_FOREGROUND`
`NetworkCapabilities.NET_CAPABILITY_NOT_RESTRICTED`
`NetworkCapabilities.NET_CAPABILITY_NOT_SUSPENDED`
`NetworkCapabilities.NET_CAPABILITY_VALIDATED`

Also, please help me check if replacing `.setRequiredNetwork(new NetworkRequest.Builder().addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET).build())` with `.setRequiredNetworkType(JobInfo.NETWORK_TYPE_ANY)` works? So that the job will not require a network that your Android system thinks it can access the internet?

Thank you.

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/61f48554992ebec15add0b27aa0cf4be2dde5275

Please test it.
