### ISSUE TITLE
Infinity crashes every time I start it after about one second of loading

### ISSUE THREAD

**Issue by JustAnotherStrange** [Docile-Alligator/Infinity-For-Reddit#173]
The app loads for one second and the first post comes up, and then it crashes. No idea as to what could have caused this.

**Comment by Mek101** [comment]
Does it work normally if you go offline, then online again and browse a subreddit instead of the home feed?

**Comment by JustAnotherStrange** [comment]
Wait, after attempting to open it about 10 times it's working again. So not as major of an issue as I thought

**Comment by Docile-Alligator** [comment]
I think it is because there is a post with a very long or high-resolution image in the post feed. Could you try quickly changing the post layout to Compact layout and find that post?

**Comment by Mek101** [comment]
@Docile-Alligator unfortunately the crash seemed to have sorted itself out by now. I had to go for a hour or so with the trick I described above before the app became functional again. It seemed to be either a connection or post issue, since clearing the cache or app data offered a couple of seconds more of usability before a crash
