### ISSUE TITLE
App shatters when going a little deep into

### ISSUE THREAD

**Issue by rustforfuture** [Docile-Alligator/Infinity-For-Reddit#182]
Hello
First, Thank you for this great client.
I am somhow eye sensitive and your client is only clean client i found. 

I think this problem started from version 4 but i don't remember exactly.

This is a video that shows the problem:
https://www5.zippyshare.com/v/JskWfItJ/file.html

Also may you please add an arm-v7 apk separately so i can test?
Because my device sometimes have problems with some arm-v8 apps and don't have same problem with arm-v7 version of them.

Thanks.

**Comment by 3j9fkyahunqoxwqu** [comment]
Also another problem that seems that be related to this is that sometimes when i open a subreddit, then i open my inbox, then post a reply to someone that commented on my comment,  then after i tap on send/post comment button after writing it, the app shows the subreddit that i opened before going to inbox instead of showing my comment that i posted now. 
I fix it by tapping on recent apps button of my device and then switching again to infinity, then infinity behave correctly  (will show the comment i replied to and my comment and after that if i press back button it correctly goes to previous screen i opened)

**Comment by Wladefant** [comment]
I am really sorry that you did not get a reply. The bugs are now out of date and fixed
