### ISSUE TITLE
Infinity crash when i download a Image. 

### ISSUE THREAD

**Issue by AntiiHeld** [Docile-Alligator/Infinity-For-Reddit#194]
I found a Bug: Infinity crash when i tap on the download button to save a Image. I made a Video: [https://youtu.be/2vmsKV8ptrI](YouTube) 

The app crashes no matter which picture, video etc. I want to save.

**Comment by Wilker-a** [comment]
this seems likely similar to #58.

do you have your Download Manager package disabled? i haven't checked for recent commits so i don't know if the app is still missing an Exception handling for this.

otherwise, you can try to use tools such as [MatLog Libre](https://f-droid.org/packages/com.pluscubed.matloglibre) to try to pinpoint where exactly does the crash occurs.

i hope it helps for now. \^\^

**Comment by AntiiHeld** [comment]
@Wilker-a I found a solution. I use Edxposed on my device. I use the Sandhook Version. I disabled Edxposed Sandhook and switch to Edxposed YAHFA and now i can download files in Infinity. But i had the download bug only in infinity. Its curious. I use matlog Libre to find the solution. I hope it helps. :)

**Comment by AntiiHeld** [comment]
Sorry, the Bug is still exists. :( I thought it was the Edxposed. But now i have the bug back.
