### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by PopeRigby** [Docile-Alligator/Infinity-For-Reddit#25]
You should probably put an open source license in this repo.

**Comment by Docile-Alligator** [comment]
ok

**Comment by Wilker-a** [comment]
[AGPL](https://choosealicense.com/licenses/agpl-3.0/) would be the best choice that i know imo :3

**Comment by PopeRigby** [comment]
That or GPLv3

**Comment by Wilker-a** [comment]
AGPL is just GPL + a clause that says that network use is considered distribution — e.g when someone uses the source code to develop a web service. SearX is an example of a web service.

AGPL is considered to be the stronger license, but GPLv3-or-later is also good i guess

**Comment by PopeRigby** [comment]
Yeah, but is the network clause needed for a simple Android app?

**Comment by Wilker-a** [comment]
i am not sure tbh.

in one hand, the original purpose is to just use the app to access Reddit from the phone, so the regular GPL would be enough, although the app is primarily for network use.

on the other hand, what happens if for some reason it ends up being used in places like Services as a Software Substitute(SaaSS)? under the regular GPL, you're not required to give the right to access the source code unless you redistribute the main software itself, so if the application is running on a server, whoever owns these servers and services can simply close-off the source code of the modified versions if they wish, so i am a bit insecure about it...

what are your thoughts on this?

**Comment by PopeRigby** [comment]
That's a fair point

**Comment by Docile-Alligator** [comment]
@PopeRigby @Wilker-a Thanks for that. I choose AGPLv3.
