### ISSUE TITLE
Video being cached over and over again in replay.

### ISSUE THREAD

**Issue by Wesley-Chan** [Docile-Alligator/Infinity-For-Reddit#265]
App version: 4.2.0

Android version: 10

Action: Click on a video.

Expected behavior: Video being cached while it plays for the first time. In replays, the phone should not show data usage and no buffering delays.

Observed behavior: In the first time and replays, the phone shows data is being used, Video lags because of buffering delay.

**Comment by Docile-Alligator** [comment]
Yes. I haven't added cache support for videos.

**Comment by mxvin** [comment]
It's quite simple to do, with some addition on `activities/ViewVideoActivity`. I've done that by creating new `SimpleCache` and put it on `cacheDir`. Then, add `CacheDataSourceFactory` and use that as MediaSource instead of original `dataSourceFactory`, append that on 4 sections/func respectively (`onCreate`, `loadGfycatOrRedgifsVideo`, `loadVReddItVideo`)
It works flawlessly, Hope it can be implement soon, but I just can't wait more for this feature 😄

**Comment by Docile-Alligator** [comment]
Thank you. @mxvin I have added this and it will be available in v4.4.0.
