### ISSUE TITLE
Bug. Not finding posts

### ISSUE THREAD

**Issue by embyveddii** [Docile-Alligator/Infinity-For-Reddit#303]
Tells me it can't find posts and to tap to retry. Checked reddit.com and that's still up so I assume it's an app problem not a reddit problem.

**Comment by tegutistgut** [comment]
Can you at least attach a log please so we can know what happened? Thx

**Comment by EmVeddii** [comment]
how the hell do I get a log? I open the app. It says there's no Internet. I can't find any log option in settings. There's just no posts because it says there's no Internet. Simple as. Redownloaded and it's still like this which makes me so so glad I moved app.

Device: Samsung Galaxy s20+ on Android 11
App: Version 4.2.5
WiFi: Fine
Patience: Gone

**Comment by tlmnot** [comment]
I got the same happen to me as well after I login and post a comment then I removed the cache files since then this happen.
