### ISSUE TITLE
Duplicate folders created as '(1), (2)' etc

### ISSUE THREAD

**Issue by nulledone** [Docile-Alligator/Infinity-For-Reddit#306]
It seems that it started appearing after I moved my downloads (completely emptied the folder), it used to be somewhat fine (there were duplicate folders but only on few, the directory was not empty at first due to the fact that I've switched from other Reddit app).

Additional info; 
Android 9
Save location: /storage/emulated/0/Android/redditdownloads

**Comment by nulledone** [comment]
A possible workaround;
Reset download location and toggle folder separation.

**Comment by nulledone** [comment]
It roughly says "Failed to save to folder, something about permissions" if I try to set different location for each (due to the fact that I was hoping one change would apply all). However, when I set each to the same location one by one, it seems to save but still folders get duplicated.

**Comment by piks** [comment]
chiming in this issue exists on Android 12 as well, error will state no storage permission and it seems once app is restarted it makes an additional folder

**Comment by piks** [comment]
@o13e the only workaround I found was the one I posted of reassigning the location on it and force restarting, but that is not a permanent workaround, currently I am just using a small script I made in NodeJS to connect to an FTP server on the phone and move the duplicate directory contents into the appropiate directory

**Comment by Wladefant** [comment]
I can not reproduce it. Please share clearer steps to reproduce and some Screenshots.

**Comment by piks** [comment]
The only way I've managed to reproduce this bug is by enabling the separate by folder option and consistently using Reddit for two or three days downloading images as I go but as requested here is an image of the current folder layout that it has auto created for my subfolders
![Screenshot_20220831-203408_My Files](https://user-images.githubusercontent.com/5431569/187808303-1ddf9d06-9122-4f1a-ad1b-1a633e238eee.jpg)

along with a screenshot of my current download settings 
![Screenshot_20220831-203734_Infinity](https://user-images.githubusercontent.com/5431569/187808424-885e4804-052d-4afe-9af1-20448c12ccd6.jpg)

**Comment by RSBat** [comment]
Found steps to reproduce on Android 12, Pixel 5:
1. Set custom download location
2. Enable "Separate folder for each subreddit" 
3. Download something. At this step everything should work fine and download into the same folder
4. Reboot device
5. Download something.  Now every download will create a new subreddit folder
