### ISSUE TITLE
It's not possible to share videos

### ISSUE THREAD

**Issue by nulledone** [Docile-Alligator/Infinity-For-Reddit#308]
It seems like there's no button to share videos directly. Instead I've to download first then share the downloaded file. Do you think of adding share feature for videos? Awesome app by the way enjoying it so far, thanks a lot!

**Comment by tegutistgut** [comment]
I think that it's possible, but if you do this, the app has to download the video in the background, and then you _would_ be able to send it to your contacts. Afterwards the video would get automatically deleted again.


That's why I _personally_ think this feature is unnecessary, but it would be a nice feature.

**Comment by electrona** [comment]
I agree this is a necessary feature as it saves a lot of time and hassle. I personally share a lot of videos.

**Comment by Docile-Alligator** [comment]
This is because the app has to mux the video and audio tracks after they are downloaded separately. This takes a lot of time so it is better to just download the video first and then click the "download complete" notification to open and share the video.
