### ISSUE TITLE
Move comment text over to the left

### ISSUE THREAD

**Issue by PopeRigby** [Docile-Alligator/Infinity-For-Reddit#35]
[It](https://fosstodon.org/@poperigby/103087671988855502) makes the comments look strange

**Comment by Docile-Alligator** [comment]
Oh I haven't thought of that

**Comment by Wilker-a** [comment]
do you mean the colored bars? because if that is the case, a setting to change their appearance would be nice. i would suggest to make them have certain colors in cases like the OP or parent commenter replying.

but also, it seems to occupy too much space on smaller screen, so they should be a bit thinner when displaying on small screens, as well as having a bit less space between the bars and the text.

what do you think?

**Comment by PopeRigby** [comment]
I was actually talking about the text, but making the bars change color for the OP might be cool.

**Comment by Docile-Alligator** [comment]
Enlarging the comment content will be available in the next update 😁

**Comment by PopeRigby** [comment]
So will that allow us to move the text over?

**Comment by Docile-Alligator** [comment]
Yes.
