### ISSUE TITLE
[BUG]  hide read posts

### ISSUE THREAD

**Issue by connerWRLD** [Docile-Alligator/Infinity-For-Reddit#390]
I have mark posts as read when i vote on it and automatically hide read posts. So when i go back on the app it never hides it.

**Comment by davidzlewis** [comment]
Mine is same way. Almost changed apps for this alone. Otherwise it's great. If I open a post and go back, its marked read. If I refresh the listing, it shows up as unread again.

**Comment by davidzlewis** [comment]
How is that a feature? I would prefer that the post is marked as read as soon as I view it. Plus, once I refresh the page they are all marked as unread again. Personally, I would prefer that once I read the posts they be hidden so that when I refresh the page or re-open the app I get as fresh view of the posts. Since this is closed I assume that you plan to leave it this way.

**Comment by Docile-Alligator** [comment]
@davidzlewis I've changed my mind. Yes, you are right. Read posts will be hidden after refresh. This change will be available in v5.1.0.

**Comment by chrisgix** [comment]
@Docile-Alligator will this also apply to read posts that aren't being hidden? So they'll stay marked read (greyed out) after refreshing?
