### ISSUE TITLE
[Feature Request] [Blue Sky] Add support for reddit alternatives like Ruqqus.com, Saidit.net, Phuks and Lemmy

### ISSUE THREAD

**Issue by ghost** [Docile-Alligator/Infinity-For-Reddit#494]
I know the app name is "Infinity for Reddit", and working for support for these website will take a while, hence the ["Blue Sky" designation ](https://github.com/d4rken/sdmaid-public/milestone/2)
Add support for the following:
[Ruqqus.com](https://github.com/ruqqus/ruqqus) and any of it's instance (i.e. someone can host their own Ruqqus instance)
[SaidIt.net](https://github.com/libertysoft3/saidit)
[Aether](https://github.com/nehbit/aether)
[Phuks](https://github.com/Phuks-co/throat)
[Lemmy](https://github.com/LemmyNet/lemmy)
[Steemit](https://github.com/steemit/steemit.com )

**Comment by MaggiWuerze** [comment]
Like you already mentioned, this is a reddit app. Which uses the reddit api to offer reddit specific functions in a reddit centric way. Asking them to now support other platforms is like asking Ford to add swimming capabilities to their cars.

This just won't happen. If you need an app for these platforms you'll have to look elsewhere or make your own.

**Comment by bevsxyz** [comment]
Since the changes on reddit api usage policy[link](https://www.reddit.com/r/redditsync/comments/12qwwjh/an_update_regarding_reddits_api_changes_to_how/), would this stance be changed. Because atleast for lemmy there is an reddit API proxy [link](https://feddit.de/post/768790)

**Comment by Mhowser** [comment]
I really love Infinity, it is the best client I have ever used for reddit. But after the api is shut off I will have to uninstall Infinity. If it had support for the federated networks I will definitely be sticking around. I'm pretty confident that there are more users who share the same outlook as I do.

Devs, please consider looking into supporting the federated networks, It is clear Reddit would rather commit Harakiri to satisfy the shareholders instead of maintaining good relationship with the users.

**Comment by MaggiWuerze** [comment]
> I understand many users want me to build a client for Lemmy, or anything that is similar, but I may not pursue this path since I personally do not use them. I heard that Lemmy has a Reddit proxy API, so I believe someone can easily convert Infinity to a Lemmy client.

https://www.reddit.com/r/Infinity_For_Reddit/comments/147bhsg/the_future_of_infinity/
