### ISSUE TITLE
Feature Request - allow saving subreddits anonymously

### ISSUE THREAD

**Issue by fusionneur** [Docile-Alligator/Infinity-For-Reddit#54]
allow saving subreddits anonymously

**Comment by fusionneur** [comment]
There's no need to login to bookmark sreddits

**Comment by Docile-Alligator** [comment]
It's a good idea but I may not implement it very soon.

**Comment by galmio** [comment]
Bumping this issue since Reddit does not allow signing up without email anymore and sign up on `i.reddit.com` is broken. This is one of the features that I miss from Slide. For reference, [this is how user subscriptions are handled on Slide](https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/UserSubscriptions.java)

**Comment by Scripterr** [comment]
Hi @Docile-Alligator , any update on this when it might be available or if this feature can be prioritized. As the above user have stated slide for reddit , (and also on red reader and dawn - foss reddit clients) have this feature and I miss it in Infinity so if you can please reconsider it would be great. Thank you.

**Comment by Github-com-foss** [comment]
Pls implement this feature as soon as possible...it is very useful feature like Newpipe.

**Comment by Docile-Alligator** [comment]
Added in 4.3.0-beta1.
