### ISSUE TITLE
Reddit live links don't respect users link handler setting

### ISSUE THREAD

**Issue by i-like-cookies** [Docile-Alligator/Infinity-For-Reddit#681]
Opening a link to a [reddit live thread](https://www.reddit.com/r/live/wiki/index) always opens it in a custom tab instead of what the user has set as their external link handler in the app settings.
An example of this is the popular currently pinned live thread in [r/worldnews](https://www.reddit.com/r/worldnews/): https://www.reddit.com/live/18hnzysb1elcs
This can be a annoying when the users browser doesn't properly show some of the live threads content (this is the case with the previously mentioned live thread and Firefox).

**Comment by Docile-Alligator** [comment]
This is intended because Infinity cannot open live thread links. If Infinity opens it in an external browser, and you have selected Infinity as the default handler for reddit.com links, then the link will never be opened.
The reason is that:
Infinity tries opening it in a browser -> Android system finds the default reddit.com link handler is Infinity -> Android asks Infinity to handle this link -> Infinity is not able to handle it -> Infinity tries opening it in a browser... This will go on infinitely and your phone will hang.
