### ISSUE TITLE
Hide download notification

### ISSUE THREAD

**Issue by test2a** [Docile-Alligator/Infinity-For-Reddit#699]
Hi 

I can't seem to find a way to not show downloading /downloaded notification. I don't need it so there should be a way to turn it off.

**Comment by Wladefant** [comment]
There is a way 
- go into app info
- go into notifications
- notification categories
- untoggle download reddit video

That is only for the video 

Or you could just disable all notifications in settings>notifications 

If your issue is resolved please consider closing it.

If you want a special toggle for that you can change the title to [Feature Request] Title and ask for this feature
