### ISSUE TITLE
Infinity stuck on old Material You color pallete, even after rebooting, clearing it's cache, and changing my wallpaper

### ISSUE THREAD

**Issue by lunandd** [Docile-Alligator/Infinity-For-Reddit#805]
So, I changed the wallpaper on my phone a few days ago. The new wallpaper, had a yellow colorscheme. Then I changed my wallpaper again. That wallpaper, my current wallpaper, has a red/pink colorscheme.

Basically, Infinity has retained the yellow colorscheme, even after rebooting, changing my wallpaper, and clearing it's cache, which is a little disappointing :(

**Comment by Docile-Alligator** [comment]
Settings->Theme->Apply Material You.

**Comment by gabey14** [comment]
> Settings->Theme->Apply Material You.

Y doesn't it auto apply when we change the system theme

**Comment by Docile-Alligator** [comment]
@gabey14 This is because Infinity has a powerful theme engine way before Material You is a thing. I understand Material You can automatically change the theme and this is done at the Android framework's level. Basically, you just specify a special color value string in a View and then Android will automatically apply the dynamic color to the View. If Infinity does this, then no matter what custom themes you have applied before, all the Views will be applied to the Material You theme. This is unacceptable. So to overcome this issue, Infinity uses a listener to know when you have changed your wallpaper. Then it gets the dynamic colors and does some modifications and finally applies them to the Views. But in order for the listener to work, Infinity should be in a running state, which means it must run before you change the wallpaper, otherwise, it will not get this info. This is why there is an option to let you manually apply Material You in Infinity.

**Comment by gabey14** [comment]
Ohk thanks for explaining it so well in depth.
