### ISSUE TITLE
Cannot send downloaded video on status Whatsapp 

### ISSUE THREAD

**Issue by H4XKER** [Docile-Alligator/Infinity-For-Reddit#820]
For some reason i can't send video even though it's mp4 format and some i can send very weird and for some reason when i convert video to MKV it work. Idk whether it's infinity reddit problem or Whatsapp. I tried to delete cache from Whatsapp and still not work

**Comment by Wladefant** [comment]
@H4XKER You are right. Just reproduced it. The whatsapp limit is 30 seconds and 16 mb, so it is not the limits fault

**Comment by Wladefant** [comment]
Just checked a bit more: The problem seems to be with the audio. You can upload easily videos with video but not without. The unavailable audio codec confuses the whatsapp status. 
I also uploaded another gif to the status and it worked just fine. 
It seems that the infinity Downloader does not handle the unavailable audio correct.
